FAT_JOKES = [
    "Yo mama is so fat that her bellybutton gets home 15 minutes before she does.",
    "Yo mama is so fat that when she was diagnosed with a flesh-eating disease, the doctor gave her ten years to live.",
    "Yo mama is so fat that the National Weather Service names each one of her farts.",
    "Yo mama is so fat that when she wears a yellow raincoat, people yell \"taxi!\"",
    "Yo mama is so fat and dumb that the only reason she opened her email was because she heard it contained spam.",
    "Yo mama is so fat she threw on a sheet for Halloween and went as Antarctica.",
    "Yo mama is so fat that she looked up cheat codes for Wii Fit",
    "Yo mama is so fat that the only exercise she gets is when she chases the ice cream truck.",
    "Yo mama is so fat that she sat on a dollar and squeezed a booger out George Washington's nose.",
    "Yo mama is so fat that when she gets in an elevator, it has to go down.",
    "Yo mama is so fat that when her beeper goes off, people think she's backing up.",
    "Yo mama is so fat that she has to iron her pants on the driveway.",
    "Yo mama is so fat that she left the house in high heels and came back wearing flip flops.",
    "Yo mama is so fat that people jog around her for exercise.",
    "Yo mama is so fat that she was floating in the ocean and Spain claimed her for the New World.",
    "Yo mama is so fat that when she walked in front of the TV, I missed 3 seasons of Breaking Bad.",
    "Yo mama is so fat that you have to grease the door frame and hold a twinkie on the other side just to get her through!",
    "Yo mama is so fat that that when she sits on the beach, Greenpeace shows up and tries to tow her back into the ocean...",
    "Yo mama is so fat that when she bungee jumps, she brings down the bridge too.",
    "Yo mama is so fat that when she talks to herself, it's a long distance call.",
    "Yo mama is so fat that the last time she saw 90210, it was on a scale.",
    "Yo mama is so fat that light bends around her.",
    "Yo mama is so fat that I took a picture of her last Christmas and it's still printing!",
    "Yo mama is so fat that when she sat on Wal-Mart, she lowered the prices.",
    "Yo mama is so fat that when she sat on an iphone, it turned into an ipad.",
    "Yo mama is so fat that even god can't lift her spirit.",
    "Yo mama is so fat that she gets group insurance.",
    "Yo mama is so fat that she was zoned for commercial development.",
    "Yo mama is so fat that she walked into the Gap and filled it.",
    "Yo mama is so fat that she comes at you from all directions.",
    "Yo mama is so fat that when she climbed onto a diving board at the beach, the lifeguard told your dad \"sorry, you can't park here\".",
    "Yo mama is so fat that her cereal bowl came with a lifeguard.",
    "Yo mama is so fat that she looks like shegs smuggling a Volkswagen.",
    "Yo mama is so fat that when she got her shoes shined, she had to take the guy's word for it.",
    "Yo mama is so fat that when she sings, it's over for everybody.",
    "Yo mama is so fat that when she ran away, they had to use all four sides of the milk carton to display her picture.",
    "Yo mama is so fat that when she was growing up she didngt play with dolls, she played with midgets.",
    "Yo mama is so fat that she uses two buses for roller-blades.",
    "Yo mama's so fat she blew up the Deathstar.",
    "Yo mama is so fat that when she goes to a buffet, she gets the group rate.",
    "Yo mama is so fat that she has to put her belt on with a boomerang.",
    "Yo mama is so fat that she broke the Stairway to Heaven.",
    "Yo mama is so fat that she doesngt eat with a fork, she eats with a forklift.",
    "Yo mama is so fat that the last time the landlord saw her, he doubled the rent.",
    "Yo mama is so fat that Weight Watchers wongt look at her.",
    "Yo mama is so fat that the highway patrol made her wear a sign saying \"Caution! Wide Turn\".",
    "Yo mama is so fat that when she sits around the house, she SITS AROUND THE HOUSE!",
    "Yo mama is so fat that when she steps on a scale, it reads \"one at a time, please\".",
    "Yo mama is so fat that she fell in love and broke it.",
    "Yo mama is so fat that when she gets on the scale it says \"We don't do livestock\".",
    "Yo mama is so fat that when she tripped on 4th Ave, she landed on 12th.",
    "Yo mama is so fat that God couldn't light the Earth until she moved!",
    "Yo mama is so fat that even Bill Gates couldn't pay for her liposuction!",
    "Yo mama is so fat that she has to pull down her pants to get into her pockets.",
    "Yo mama is so fat that she was born on the fourth, fifth, and sixth of June.",
    "Yo mama is so fat that she could fall down and wouldngt even know it.",
    "Yo mama is so fat that the sign inside one restaurant says, “Maximum occupancy: 300, or Yo momma.”",
    "Yo mama is so fat that she puts mayonnaise on aspirin.",
    "Yo mama is so fat that she was born with a silver shovel in her mouth.",
    "Yo mama is so fat that when she hauls ass, she has to make two trips.",
    "Yo mama is so fat that she had to go to Sea World to get baptized.",
    "Yo mama is so fat that her bellybuttongs got an echo.",
    "Yo mama is so fat that when she turns around people throw her a welcome back party.",
    "Yo mama is so fat that her belly button doesngt have lint, it has sweaters.",
    "Yo mama is so fat that a picture of her would fall off the wall.",
    "Yo mama is so fat that when she takes a shower, her feet dongt get wet.",
    "Yo mama is so fat that she puts on her lipstick with a paint-roller!",
    "Yo mama is so fat that she could sell shade.",
    "Yo mama is so fat that I ran around her twice and got lost.",
    "Yo mama is so fat that the shadow of her butt weighs 100 pounds.",
    "Yo mama is so fat that when shegs standing on the corner police drive by and yell, “Hey, break it up.”",
    "Yo mama is so fat that her blood type is Ragu.",
    "Yo mama is so fat that when she runs the fifty-yard dash she needs an overnight bag.",
    "Yo mama is so fat that she cangt even fit into an AOL chat room.",
    "Yo mama is so fat when she goes skydiving she doesn't use a parachute to land, she uses a twin-engine plane!",
    "Yo mama is so fat MTX audio's subwoofers couldn't rattle her bones!",
    "Yo mama is so fat her headphones are a pair of PA speakers connected to a car amplifier.",
    "Yo mama is so fat that she doesngt have a tailor, she has a contractor.",
    "Yo mama is so fat that eating contests have banned her because she is unfair competition.",
    "Yo mama is so fat that she measures 36-24-36, and the other arm is just as big.",
    "Yo mama is so fat that she gets her toenails painted at Luckygs Auto Body.",
    "Yo mama is so fat that when she goes to an amusement park, people try to ride HER!",
    "Yo mama is so fat that when she jumps up in the air she gets stuck!",
    "Yo mama is so fat that she has more Chins than a Chinese phone book!",
    "Yo mama is so fat that she influences the tides.",
    "Yo mama is so fat that when she plays hopscotch, she goes \"New York, L.A., Chicago...\"",
    "Yo mama is so fat that NASA has to orbit a satellite around her!",
    "Yo mama is so fat that when she sits on my face I can't hear the stereo.",
    "Yo mama is so fat that they have to grease the bath tub to get her out!",
    "Yo mama is so fat that she's on both sides of the family!",
    "Yo mama is so fat that at the zoo, the elephants throw HER peanuts.",
    "Yo mama is so fat you have to roll over twice to get off her.",
    "Yo mama is so fat that she sets off car alarms when she runs.",
    "Yo mama is so fat that she cant reach into her back pocket.",
    "Yo mama is so fat that she has her own gravity field.",
    "Yo mama is so fat that she stepped on a rainbow and made Skittles.",
    "Yo mama is so fat that the only pictures you have of her were taken by satellite cameras.",
    "Yo mama is so fat that when she wears a \"Malcolm X\" T-shirt, helicopters try to land on her back!",
    "Yo mama is so fat that it took Usain Bolt 3 years to run around her.",
    "Yo mama so fat that she sweats more than a dog in a chinese restaurant.",
    "Yo mama so fat, that went she stepped in the water, Thailand had to declare another tsunami warning.",
    "Yo mama is so fat that that she cant tie her own shoes.",
    "Yo mama is so fat that when she lays on the beach, people run around yelling Free Willy.",
    "Yo mama is so fat that she uses redwoods to pick her teeth",
    "Yo mama is so fat that she cut her leg and gravy poured out",
    "Yo mama is so fat that she was in the Macygs Thanksgiving Day Parade... wearing ropes.",
    "Yo mama is so fat that she went on a light diet. As soon as it's light she starts eating.",
    "Yo mama is so fat that shegs half Italian, half Irish, and half American.",
    "Yo mama is so fat that her waist size is the Equator.",
    "Yo mama is so fat that she cangt even jump to a conclusion.",
    "Yo mama is so fat that she uses a mattress for a tampon.",
    "Yo mama is so fat that when she got hit by a bus, she said, \"Who threw that rock at me?\"",
    "Yo mama is so fat that we went to the drive-in and didn't have to pay for her because we dressed her up as a Toyota.",
    "Yo mama is so fat that when she was born, she gave the hospital stretch marks.",
    "Yo mama is so fat that she was cut from the cast of E.T., because she caused an eclipse when she rode the bike across the moon.",
    "Yo mama is so fat that when you get on top of her your ears pop.",
    "Yo mama is so fat that she got hit by a car and had to go to the hospital to have it removed.",
    "Yo mama is so fat that she eats \"Wheat Thicks\".",
    "Yo mama is so fat that we're in her right now!",
    "Yo mama is so fat that she went to the movie theatre and sat next to everyone.",
    "Yo mama is so fat that she has been declared a natural habitat for condors.",
    "Yo mama is so fat that when she wants to shake someones hand, she has to give directions!",
    "Yo mama is so fat that even Dora can't explore her!",
    "Yo mama is so fat that when she gets on the scale it says \"to be continued\".",
    "Yo mama is so fat that when she goes to a resturant, she looks at the menu and says \"okay!\"",
    "Yo mama is so fat that even Chuck Norris couldn't run around her.",
    "Yo mama is so fat that her neck looks like a dozen hot dogs!",
    "Yo mama is so fat that when she bungee jumps she goes straight to hell!",
    "Yo mama is so fat that she's got her own area code!",
    "Yo mama is so fat that she looks like she's smuggling a Volkswagon!",
    "Yo mama is so fat that she has to buy three airline tickets.",
    "Yo mama is so fat that whenever she goes to the beach the tide comes in!",
    "Yo mama is so fat that she's got Amtrak written on her leg.",
    "Yo mama is so fat that her legs are like spoiled milk - white & chunky!",
    "Yo mama is so fat that I had to take a train and two buses just to get on the her good side!",
    "Yo mama is so fat that she wakes up in sections!",
    "Yo mama so fat, all she wants for Christmas is to see her feet.",
    "Yo mama is so fat that when she lies on the beach no one else gets any sun!",
    "Yo mama is so fat that that her senior pictures had to be taken from a helicopter!",
    "Yo mama is so fat that everytime she walks in high heels, she strikes oil!",
    "Yo mama is so fat that she fell and created the Grand Canyon!",
    "Yo mama is so fat that her butt drags on the ground and kids yell - \"there goes santa claus with his bag of toys!\"",
    "Yo mama is so fat that even her clothes have stretch marks!",
    "Yo mama is so fat that she has to use a VCR as a beeper!",
    "Yo mama is so fat that when she asked for a waterbed, they put a blanket over the ocean!",
    "Yo mama is so fat that she got hit by a parked car!",
    "Yo mama is so fat that they use the elastic in her underwear for bungee jumping.",
    "Yo mama is so fat that when we were playing Call of Duty, I got a 20 kill streak for killing her.",
    "Yo mama is so fat that Dracula got Type 2 Diabetes after biting her neck.",
    "Yo mama is so fat that when she visited Toronto's City Hall, she was arrested for attempting to smuggle 500 lbs of crack into Mayor Rob Ford's office.",
    "Yo mama is so fat that when she fell over she rocked herself asleep trying to get up again.",
    "Yo mama is so fat that that when I tried to drive around her I ran out of gas.",
    "Yo mama is so fat that when she went to church and sat on a bible, Jesus came out and said \"LET MY PEOPLE GO!\"",
    "Yo mama is so fat that when she dances at a concert the whole band skips.",
    "Yo mama is so fat that she stands in two time zones.",
    "Yo mama is so fat that she went to the fair and the kids thought she was a bouncy castle.",
    "Yo mama is so fat that when she goes to an all you can eat buffet, they have to install speed bumps.",
    "Yo mama is so fat that the camera TAKES AWAY 10 lbs from her appearance.",
    "Yo mama is so fat that her sedan can fit 5 people... or just yo mama with the front seats removed.",
    "Yo mama is so fat that when she went to seaworld the whales started singing \"We Are Family\".",
    "Yo mama is so fat that she fell out of both sides of her bed.",
    "Yo mama is so fat that the stripes on her pajamas never end.",
    "Yo mama is so fat, Al Gore accuses her of global warning everytime she farts!",
    "Yo mama is so fat that she's got every caterer in the city on speed dial!",
    "Yo mama's so fat that when she goes on a scale, it shows her own phone number.",
    "Yo mama's so fat that she doesn't need the internet - she's worldwide.",
    "Yo mama's so fat that when she goes on a scale, it reads \"lose some weight\".",
    "Yo mama's so fat that she doesn't get dreams, she gets movies!",
    "Yo mama's so fat that when she walks, she changes the earth's rotation!",
    "Yo mama is so fat that she uses the entire country of Mexico as her tanning bed.",
    "Yo mama's so fat that the Sorting Hat put her in all four houses!",
    "Yo mama's so fat that a wingardium leviosa spell couldn't lift her.",
    "Yo mama's so fat, she makes Hagrid look like \"Mini-me\".",
    "Yo mama's so fat, she tried to eat Cornelius Fudge.",
    "Yo Mama's so fat, her Patronus is a Double-Whopper with Cheese.",
    "Yo mama is so fat that she took geometry in high school just cause she heard there was gonna be some pi.",
    "Yo mama is so fat that the ratio of the circumference to her diameter is four.",
    "Yo mama is so fat that her derivative is strictly positive.",
    "Yo mama is so fat that in a love triangle, she'd be the hypotenuse.",
    "Yo mama's so fat that when she asked me \"what's up?\" I said \"your weight!\"",
    "Yo mama's so fat the Sorting Hat assigned her to the House of Pancakes.",
    "Yo mama's so fat, she used the invisibility cloak as a bib.",
    "Yo mama's so fat that even the Dementors can't suck her soul out in one sitting.",
    "Yo mama's so fat, she looked in the mirror of Erised and saw a ham!",
    "Yo mama's so fat that if she confronted a boggart it would morph into a treadmill.",
    "Yo mama's so fat that the sorting hat couldn't decide where to put her - she couldn't fit in any of the houses!!",
    "Yo mama's so fat, she ate the Death Eaters.",
    "Yo mama's so fat that it takes two boggarts to shape-shift into her!",
    "Yo mama's so fat that even her Quidditch robes have stretch marks.",
    "Yo mama's so fat even Grawp can't pick her up!",
    "Yo mama's so fat they'd have to use transfiguration to sneak her through the hole in the Gryffindor Tower.",
    "Ya mama's so fat, her wand is a Slim Jim.",
    "Yo mama's so fat the core of her wand has a creame filling.",
    "Yo mama's so fat that a $700 billion bailout would only keep her fed for a week.",
    "Yo mama's so fat that the housing bubble popped because she sat on it!",
    "Yo mama's so fat that she supported the bailout just because she wanted a 'barrel of pork'.",
    "Yo mama's so fat that even Mitt Romney couldn't afford to take her out to dinner!",
    "Yo mama's so fat that her biography is called \"The Audacity of Hardee's\".",
    "Yo mama's so fat that Sarah Palin can see her from her house.",
    "Yo mama's so fat that Sarah Palin can't see Russia anymore!.",
    "Yo mama's so fat that \"ACORN\" registered her to vote eight times!",
    "Yo mama's so fat that even the Death Star couldn't blow her up!",
    "Yo mama's so fat that Spock couldn't find a pressure point to perform the Vulcan Death Grip on her.",
    "Yo mama's so fat the odds against not finding her fat are approximately 3,720 to 1.",
    "Yo mama's so fat that she thought the opening line of Kirk's monologue was \"Spice, the final Frontier...\"",
    "Yo mama's so fat that if she were placed beside a changeling during regeneration, no one would know the difference.",
    "Yo mama's so fat that she tried to fly through a temporal anomoly but she didn't fit.",
    "Yo mama's so fat she makes Riker's belly look 3 atoms thick.",
    "Yo mama's so fat that when she tried to captain a galaxy class they had to separate the saucer so she could fit.",
    "Yo mama's so fat that she makes the USS Enterprise look like a micro machines racer.",
    "Yo mama's so fat that Dexster Jettster mistook her for his wife.",
    "Yo mama's so fat that only half her body was able to come out frozen from the carbon freezing chamber in Cloud City.",
    "Yo mama's so fat that when she beams to a ship, the ship beams inside of her.",
    "Yo mama's so fat that the passengers of the Millenium Falcon mistook her for a small moon.",
    "Yo mama's so fat that Gardulla the Hutt had a boost in self-esteem after seeing her.",
    "Yo mama's so fat that she fell to the dark side and couldn't get back up.",
    "Yo mama's so fat that if she was thrown into the second Death Star's reactor core, she could have blown up the entire Imperial fleet.",
    "Yo mama's so fat that the Kaminoans couldn't use her as a host for clones since they couldn't pierce her skin deep enough to draw blood.",
    "Yo mama's so fat that she caused Kamino to flood when her water broke.",
    "Yo mama's so fat that her lack of balance caused her to stumble into an Utapau sinkhole.",
    "Yo mama's so fat that she crushed Boga as soon as she mounted her.",
    "Yo Mama's so fat, that in an attempt to beam her up, the ship ended up being pulled down to the surface.",
    "Yo Mama's so fat that when she walks into a room the replicators stop working.",
    "Yo Mama's so fat, Data feels strong emotions of disgust and self-terminates.",
    "Yo Mama's so fat she wears her own inertia dampener.",
    "Yo Mama's so fat, she managed to contain a warp core breach.",
    "Yo Mama's so fat, she got stuck trying to enter the Nexus.",
    "Yo Mama's so fat, when she fell over, she punched a hole in the fabric of space/time.",
    "Yo mama's so fat that when she stepped on the scale, her weight was OVER 9000!!!",
    "Yo Mama's so fat, she walked in front of the TV and I missed three seasons of Inuyasha!",
    "Yo mama's so fat, Naruto couldnt make enough clones to see all sides of her.",
    "Yo mama's so fat that the Dragon Ball Z crew uses her to make craters on set.",
    "Yo mama's so fat that when she sat down on a park bench, she caused the Naruto timeskip.",
    "Yo mama's so fat, she scared L into giving up all sweets.",
    "Yo mama's so fat that she cant even fit in the expanding plug suit.",
    "Yo mama's so fat that she broke the HP limit!",
    "Yo mama's so fat, she makes Vash look anorexic!",
    "Yo Mama So Fat, she can't fit through the moon door.",
    "Yo mama's so fat that she was mistaken for Mt. Fuji at the Sakura festival.",
    "Yo mama's so fat she makes a Snorlax look like a chihuahua!",
    "Yo mama's so fat that it took the entire Dragon Ball Z crew 1 week just to lift her off the ground.",
    "Yo mama's so fat that she tried to eat someone dressed as a box of Pocky!",
    "Yo mama's so fat, Choji told her to lose weight.",
    "Yo mama so fat, they've been calling her \"the wall\" for thousands of years!",
    "Yo mama so fat, she Winter-fell and couldn't get up!",
    "Yo mama so fat, even Roose Bolton won't touch her",
    "Yo mama's so fat that she expresses her weight in scientific notation.",
    "Yo mama's so fat that scientists track her position by observing anomalies in Pluto's orbit.",
    "Yo mama's so fat that a recursive function computing her weight causes a stack overflow.",
    "Yo mama's so fat that the long double numeric variable type in C++ is insufficient to express her weight.",
    "Yo mama's so fat that THX can't even surround her.",
    "Yo mama's so fat that she and the great wall of China are used as reference points when astronauts look back at the Earth.",
    "Yo mama's so fat that China uses her to block the internet.",
    "Yo mama's so fat that NASA shot a rocket into her ass looking for water.",
    "Yo mama's so fat that she doesn't just have a low center of gravity, she has an elliptical orbit.",
    "Yo mama's so fat that IEEE is working on a wifi protocol so people can get the signals to reach users on opposite sides of her. It's called 802.11 Draft Fat Momma",
    "Yo mama's so fat, the cyberman DOWNgraded her.",
    "Yo mama's so fat, she's bigger than both the outside AND the inside of the Tardis",
    "Yo mama's so fat, the Pirate Planet tried to take her over.",
    "Yo Mama's so fat that when she got upgraded by the cybermen, they turned her into an ice cream truck",
    "Yo mama's so fat, the Doctor caught her eating his psychic paper, thinking it was a burger.",
    "Yo mama's so fat, it doesn't matter that the Tardis is bigger on the inside. She can't get through the door.",
    "Yo mama is so fat that Thanos had to snap his fingers twice to make her disappear."
]

DUMB_JOKES = [
    "MacGyver can build an airplane out of gum and paper clips. Chuck Norris can kill him and take it.",
    "Chuck Norris is the only human being to display the Heisenberg uncertainty principle - you can never know both exactly where and how quickly he will roundhouse-kick you in the face.",
]

STUPID_JOKES = [
    "Yo mama is so stupid that it took her 2 hours to watch 60 Minutes!",
    "Yo mama is so stupid that when your dad said it was chilly outside, she ran out the door with a spoon.",
    "Yo mama is so stupid that when she saw the \"Under 17 not admitted\" sign at a movie theatre, she went home and got 16 friends.",
    "Yo mama is so stupid that when she went for a blood test, she asked for time to study.",
    "Yo mama is so stupid that she got locked in a grocery store and starved!",
    "Yo mama is so stupid that you have to dig for her IQ!",
    "Yo mama is so stupid that she tripped over a cordless phone!",
    "Yo mama is so stupid that she sold her car for gas money!",
    "Yo mama is so stupid that she told everyone that she was \"illegitimate\" because she couldn't read.",
    "Yo mama is so stupid that that she tried to put M&M's in alphabetical order!",
    "Yo mama is so stupid that she took the Pepsi challenge and chose Dr. Pepper.",
    "Yo mama is so stupid that she thought Delta Airlines was a sorority.",
    "Yo mama is so stupid that she thinks Fleetwood Mac is a new hamburger at McDonalds!",
    "Yo mama is so stupid that she bought a videocamera to record cable tv shows at home.",
    "Yo mama is so stupid that when she read on her job application to not write below the dotted line she put \"OK\".",
    "Yo mama is so stupid that she thought Grape Nuts was an STD.",
    "Yo mama is so stupid that she spent twenty minutes lookin' at an orange juice box because it said \"concentrate\".",
    "Yo mama is so stupid that she asked me what yield meant, I said \"Slow down\" and she said \"What... does.... yield... mean?\"",
    "Yo mama is so stupid that she thought Dunkin' Donuts was a basketball team!",
    "Yo mama is so stupid that she put a phone up her ass and thought she was making a booty call.",
    "Yo mama is so stupid that she thinks Tiger Woods is a forest in India.",
    "Yo mama is so stupid that she put on her glasses to watch 20/20.",
    "Yo mama is so stupid that she climbed over a glass wall to see what was behind it.",
    "Yo mama is so stupid that she failed a survey.",
    "Yo mama is so stupid that she stopped at a stop sign and waited for it to say go.",
    "Yo mama is so stupid, she went to the aquarium to buy a Blu-Ray.",
    "Yo mama is so stupid that I told her I was reading a book by Homer and she asked if I had anything written by Bart.",
    "Yo mama is so stupid that she tried to commit suicide by jumping out of the basement window.",
    "Yo mama is so stupid that she needs twice as much sense to be a half-wit.",
    "Yo mama is so stupid that she thought brownie points were coupons for a bake sale.",
    "Yo mama is so stupid that when the computer said \"Press any key to continue\", she couldn't find the 'Any' key.",
    "Yo mama is so stupid that she thought Tupac Shakur was a Jewish holiday.",
    "Yo mama is so stupid that when I was drowning and yelled for a life saver, she said \"Cherry or Grape?\"",
    "Yo mama is so stupid that she sat in a tree house because she wanted to be a branch manager.",
    "Yo mama is so stupid that I saw her jumping up and down, asked what she was doing, and she said she drank a bottle of medicine and forgot to shake it.",
    "Yo mama is so stupid that when she locked her keys in the car, it took her all day to get Yo family out.",
    "Yo mama is so stupid that she got locked out of a convertible car with the top down.",
    "Yo mama is so stupid that when she pulled into the drive-thru at McDonald's, she drove through the window.",
    "Yo mama is so stupid that she put 2 quarters in her ears and thought she was listening to 50 cent.",
    "Yo mama is so stupid that she was on the corner with a sign that said \"Will eat for food.\"",
    "Yo mama is so stupid that in the 'No Child Left Behind' act there's a provision that exempts yo mama.",
    "Yo mama is so stupid that she got locked in a Furniture store and slept on the floor.",
    "Yo mama is so stupid that she peals M&M's to make chocolate chip cookies.",
    "Yo mama is so stupid that she leaves the house for the Home Shopping Network.",
    "Yo mama is so stupid that she brought a cup to the movie \"Juice.\"",
    "Yo mama is so stupid that she thinks fruit punch is a gay boxer.",
    "Yo mama is so stupid that she uses Old Spice for cooking.",
    "Yo mama is so stupid that she threw a rock the ground and missed.",
    "Yo mama is so stupid that she went to the store to buy a color TV and asked what colors they had.",
    "Yo mama is so stupid that she tries to email people by putting envelopes into her computer's disk drive.",
    "Yo mama is so stupid that when she took an IQ test, the results came out negative.",
    "Yo mama's so stupid that she though Jar-Jar came with Pickles-Pickles.",
    "Yo mama is so stupid that she thought St. Ides was a Catholic church.",
    "Yo mama is so stupid that she puts lipstick on her head just to make-up her mind",
    "Yo mama is so stupid that she thought she needed a token to get on Soul Train.",
    "Yo mama is so stupid, that she thought Moby Dick was a sexually transmitted disease.",
    "Yo mama is so stupid that she makes Beavis and Butt-Head look like Nobel Prize winners.",
    "Yo mama is so stupid that she took a spoon to the superbowl.",
    "Yo mama is so stupid that that she thought Boyz II Men was a day care center.",
    "Yo mama is so stupid that she got stabbed in a shoot out.",
    "Yo mama is so stupid that she sits on the TV, and watches the couch!",
    "Yo mama is so stupid that she took a umbrella to see Purple Rain.",
    "Yo mama is so stupid that she ordered her sushi well done.",
    "Yo mama is so stupid that she got fired from the M&M factory for throwing away all the W's.",
    "Yo mama is so stupid that she put on a coat to chew winterfresh gum.",
    "Yo mama is so stupid that she put a quarter in a parking meter and waited for a gumball to come out.",
    "Yo mama is so stupid that she ordered a cheese burger from McDonald's and said \"Hold the cheese.\"",
    "Yo mama is so stupid that she thinks Taco Bell is a Mexican Phone Company.",
    "Yo mama is so stupid that she thinks Christmas Wrap is Snoop Dogg's holiday album.",
    "Yo mama is so stupid that she ran outside with a purse because she heard there was change in the weather.",
    "Yo mama is so stupid that I told her Christmas was just around the corner and she went looking for it.",
    "Yo mama is so stupid that she wiped her ass before she took a shit.",
    "Yo mama is so stupid that she tries to insult you with yo mama jokes.",
    "Yo mama is so stupid that she put a peephole in a glass door.",
    "Yo mama is so stupid that I saw her in the frozen food section with a fishing rod.",
    "Yo mama is so stupid that when she heard 90% of all crimes occur around the home, she moved.",
    "Yo mama is so stupid that when she saw a \"Wrong Way\" sign in her rearview mirror, she turned around.",
    "Yo mama is so stupid that she shoved a AA battery up her butt and said \"I got the power!\"",
    "Yo mama is so stupid that she called the 7-11 to see when they closed.",
    "Yo mama is so stupid that she sold the house to pay the mortgage.",
    "Yo mama is so stupid that when I asked her about X-Men she said \"Sure, there's Bobby my first baby daddy, Roger the guy I see on Thursdays...\"",
    "Yo mama is so stupid that she thought meow mix was a record for cats.",
    "Yo mama is so stupid that she took lessons for a player piano.",
    "Yo mama is so stupid that she said \"what's that letter after x\" and I said Y she said \"Cause I wanna know\".",
    "Yo mama is so stupid that when she asked me what kinda jeans I wore, I said Guess and she said \"Ummm... Levis?\"",
    "Yo mama is so stupid that if she spoke her mind, she'd be speechless.",
    "Yo mama is so stupid that it takes her an hour to cook minute rice.",
    "Yo mama is so stupid that she asked for a price check at the dollar store.",
    "Yo mama is so stupid that on her job application where it says emergency contact she put 911.",
    "Yo mama is so stupid that she can't make Jello because she can't fit 2 quarts of water in the box.",
    "Yo mama is so stupid that she thinks a stereotype is the brand on her clock-radio.",
    "Yo mama is so stupid that she thought a lawsuit was something you wear to court.",
    "Yo mama is so stupid that she thinks sexual battery is something in a dildo.",
    "Yo mama is so stupid that the first time she used a vibrator, she cracked her two front teeth.",
    "Yo mama is so stupid that she sent me a fax with a stamp on it.",
    "Yo mama is so stupid that I saw her walking down the street yelling into an envelope, asked what she was doing, and she said sending a voice mail.",
    "Yo mama is so stupid that she tried to drown a fish.",
    "Yo mama is so stupid that if you gave her a penny for her thoughts, you'd get change.",
    "Yo mama is so stupid that she thought Mick Jagger was a breakfast sandwich!",
    "Yo mama is so stupid that when she heard her neighbour was spanking the monkey, she called the humane society.",
    "Yo mama is so stupid that when she took you to the airport and a sign said \"Airport Left,\" she turned around and went home.",
    "Yo mama is so stupid that when she went to take the 44 bus, she took the 22 twice instead.",
    "Yo mama is so stupid that she asked you \"What is the number for 911?\"",
    "Yo mama is so stupid that she thinks a quarterback is a refund!",
    "Yo mama is so stupid that she bought a solar-powered flashlight!",
    "Yo mama is so stupid that she took a ruler to bed to see how long she slept.",
    "Yo mama is so stupid that she thought menopause was a button on the VCR.",
    "Yo mama is so stupid that she picked up the phone and asked \"What button do I push?\"",
    "Yo mama is so stupid that when she worked at McDonald's and someone ordered small fries, she said \"Hey Boss, all the small one's are gone.\"",
    "Yo mama is so stupid that she got hit by a parked car.",
    "Yo mama is so stupid that when her husband lost his marbles she ran to the store and bought him new ones.",
    "Yo mama is so stupid that when they said they were playing craps she went and got toilet paper.",
    "Yo mama is so stupid that when I asked her if she wanted to play one on one, she said \"Ok, but what's the teams?\"",
    "Yo mama is so stupid that she thinks Johnny Cash is a pay toilet!",
    "Yo mama is so stupid that when the judge said \"Order in the court,\" she said \"I'll have a hamburger and a Coke.\"",
    "Yo mama is so stupid that she wiped her ass before she took a shit.",
    "Yo mama is so stupid that she thinks socialism means partying!",
    "Yo mama is so stupid that when asked on an application, \"Sex?\", she marked, \"M, F, and wrote sometimes Wednesday too.\"",
    "Yo mama is so stupid that she thinks deadbeat is a type of music.",
    "Yo mama is so stupid that she thinks Tiger Woods is a forest.",
    "Yo mama is so stupid that she put two M&M's in her ears and thought she was listening to Eminem.",
    "Yo mama is so stupid that at bottom of application where it says Sign Here - she put Scorpio.",
    "Yo mama is so stupid that she wouldn't know up from down if she had three guesses.",
    "Yo mama is so stupid that she once attempted to commit suicide by jumping off a curb.",
    "Yo mama is so stupid that she put on bug spray before going to the flea market.",
    "Yo mama is so stupid that she stole free bread.",
    "Yo mama is so stupid that she locked her keys inside a motorcycle.",
    "Yo mama's so stupid that she got locked inside a motorcycle.",
    "Yo mama's so stupid that she went to the dentist to get a bluetooth.",
    "Yo mama's so stupid that she bought tickets to Xbox Live.",
    "Yo mama's so stupid that whenever someone rings the doorbell, she checks the microwave.",
    "Yo mama's so stupid that when she broke her VCR, she bought a video tape on how to fix your VCR.",
    "Yo mama is so stupid that she tried to drop acid but the car battery fell on her foot.",
    "Yo mama so dumb, she lost a spelling bee to Hodor",
    "Yo Mama so dumb, she thought Bran Stark was a type of muffin."
]